import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import dbConnect from "@/lib/dbConnect.js";
import CookieConsent from "@/components/CookieConsent";
import CustomProvider from "@/store/customProvider";
import { NavBarDemo } from "@/components/Navbar";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Round-Robin Coupon Distribution with Abuse Prevention",
  description: "Generated by create next app",
};

dbConnect();

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ToastContainer/>
        <NavBarDemo/>
        <CustomProvider>

        {children}
        </CustomProvider>
        <CookieConsent/>
      </body>
    </html>
  );
}
